@host = http://localhost:8000

# We will use this later for authentication
@token = AN_EXAMPLE_TOKEN

### Create artifact: Trail Camera
# @name create_camera
POST {{host}}/api/artifact/create
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
  "name": "Trail Camera",
  "description": "Solar powered, motion-activated camera",
  "location": { "lat": 42.391, "lon": -72.526, "alt": 92.5 },
  "parent_id": 1
}

### Create artifact: Spare Battery
# @name create_battery
POST {{host}}/api/artifact/create
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
  "name": "Spare Battery",
  "description": "Lithium pack for the trail cam",
  "location": { "lat": 42.392, "lon": -72.527 },
  "parent_id": {{create_camera.response.body.$.id}}
}

### Get artifact by id (from the first create)
GET {{host}}/api/artifact/{{create_camera.response.body.$.id}}
Authorization: Bearer {{token}}
Accept: application/json

### Get artifact by id (hardcoded example)
GET {{host}}/api/artifact/1
Authorization: Bearer {{token}}
Accept: application/json
